### ISSUE TITLE
fixing android navigation bar popping up in apps that don't use it

### ISSUE THREAD

**Issue by hrodric-baptista** [ladjs/react-native-loading-spinner-overlay#119]
I am having an issue with my app that's fairly annoying.
By default, my app hides the android navigation bar as soon as it loads, this is because it isn't really needed and the user can swipe up whenever he wants to leave the app.
Problem: Everytime the spinner is loaded, the navigation bar pops up for how much time the app takes loading, for example, if one of my screen takes 2 seconds to load, the action bar pops up with a white color, causes the whole view to shift and overall looks straight up bad.
Expected Output: The spinner is shown but the navigation bar doesn't pop up, this is because in my app I am already setting it to be hidden and if the user wants to interact with it he can just swipe up.
This is what I mean by navigation bar: [https://i.stack.imgur.com/Di9iT.png](url)

Also, this is the code for hiding the navigation bar: 

```
NavigationBar.setBehaviorAsync('overlay-swipe')
NavigationBar.setVisibilityAsync('hidden')
```

**Comment by hrodric-baptista** [comment]
solved

**Comment by jimdog1001** [comment]
> solved

how did you solve this?
